### ISSUE TITLE
 Broken with the new Discord CSS update

### ISSUE THREAD

**Issue by iblowmymind** [CreArts-Community/Context-Icons#10]
Discord decided to rename, like, 90% of its CSS classes, so the theme doesn't work at the moment.

**Comment by CorellanStoma** [comment]
@iblowmymind Hi, yeah I know, I fixed:

Friends-Grid
Context-Icons
Settings-Icons

so far. I'll push the updates later.

**Comment by iblowmymind** [comment]
Thank you! Closing the issue.
