### ISSUE TITLE
Missing Report Raid Icon

### ISSUE THREAD

**Issue by zachjmurphy** [CreArts-Community/Context-Icons#16]
![image](https://user-images.githubusercontent.com/106167296/180587127-f81f7a01-446c-42f6-a9de-eee2de510b32.png)

This is not a plugin.

**Comment by asportnoy** [comment]
What icon would it be? The icon on the right is already in use for the privacy icon so that wouldn't work.

**Comment by zachjmurphy** [comment]
> 

Shield Icon?

**Comment by asportnoy** [comment]
>  The icon on the right is already in use for the privacy icon so that wouldn't work.

**Comment by zachjmurphy** [comment]
> > The icon on the right is already in use for the privacy icon so that wouldn't work.

I know the icon on the right is already in use. I was thinking of something like this: 
![image](https://user-images.githubusercontent.com/106167296/180587295-88d929c5-41ce-4ba3-a057-5f73effe9486.png)

**Comment by zachjmurphy** [comment]
Or something like this: 
![image](https://user-images.githubusercontent.com/106167296/180587307-b52627ae-4fdc-4d3c-9593-540935565bb5.png)

**Comment by asportnoy** [comment]
<img width="142" alt="Screenshot on 2022-07-22 at 21 32 44" src="https://user-images.githubusercontent.com/14863373/180587335-5d22c0b8-8ac7-44fb-8aed-d17dd7d20d43.png">
How about this

**Comment by zachjmurphy** [comment]
> <img alt="Screenshot on 2022-07-22 at 21 32 44" width="142" src="https://user-images.githubusercontent.com/14863373/180587335-5d22c0b8-8ac7-44fb-8aed-d17dd7d20d43.png">
> How about this

That looks good.

**Comment by asportnoy** [comment]
<img width="221" alt="Screenshot on 2022-07-22 at 21 36 31" src="https://user-images.githubusercontent.com/14863373/180587438-6fe33ec5-8b22-47dd-aa1b-e2d9ea0944c4.png">
Hm, doesn't look quite right

**Comment by zachjmurphy** [comment]
> <img alt="Screenshot on 2022-07-22 at 21 36 31" width="221" src="https://user-images.githubusercontent.com/14863373/180587438-6fe33ec5-8b22-47dd-aa1b-e2d9ea0944c4.png">
> Hm, doesn't look quite right

Maybe increase the size?

**Comment by asportnoy** [comment]
<img width="223" alt="Screenshot on 2022-07-22 at 21 42 49" src="https://user-images.githubusercontent.com/14863373/180587634-e9ac9102-66e1-4aa8-9fd5-13dc95f293b9.png">
Much better

**Comment by zachjmurphy** [comment]
That for sure looks better. However the "Leave Server" icon looks off imo.

**Comment by asportnoy** [comment]
That's outside the scope of my PR so you should create a separate issue for it or PR it yourself. I'd probably use this icon though:
![Exit_(6aaa379d992c5b412d6412b3df9ff477)](https://user-images.githubusercontent.com/14863373/180587686-cd48cc23-76da-44c7-8706-c56475915c9e.svg)

**Comment by zachjmurphy** [comment]
> 

Okay. Thank You.
